# Generated by Django 2.2.4 on 2021-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTurnoverRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_turnover_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cash_change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashConversionCycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cash_conversion_cycle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cash_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompaniesGeneral',
            fields=[
                ('ticker', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('authorized_capital', models.FloatField(blank=True, null=True)),
                ('issued_shares', models.FloatField(blank=True, null=True)),
                ('paid_capital', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentAssets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'current_assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'current_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DaysInventoryOutstanding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'days_inventory_outstanding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DaysPayableOutstanding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'days_payable_outstanding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DaysSalesOutstanding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'days_sales_outstanding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'debt_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtToEquity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'debt_to_equity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DividendsPerShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dividends_per_share',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DividendYield',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dividend_yield',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ebit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ebit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ebitda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ebitda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquityToCapital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equity_to_capital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquityTurnoverRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equity_turnover_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTurnoverRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_turnover_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marketcap',
            fields=[
                ('ticker', models.IntegerField(primary_key=True, serialize=False)),
                ('marketcap', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketcap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetFixedAssetTurnoverRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'net_fixed_asset_turnover_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetMargin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'net_margin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonCurrentAssets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'non_current_assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatingCycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operating_cycle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatingEps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operating_eps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatingProfitMargin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operating_profit_margin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatingProfitMultiple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operating_profit_multiple',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayableTurnoverRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payable_turnover_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayoutRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payout_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuickRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quick_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivablesTurnoverRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receivables_turnover_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalLiabilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'total_liabilities',
                'managed': False,
            },
        ),
    ]
