# Generated by Django 2.2.4 on 2021-08-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendIndustryAverage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('Average', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
