# Generated by Django 2.2.4 on 2021-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0002_dividendindustryaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendindustryaverage',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
